// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, non_constant_identifier_names, unused_import, duplicate_ignore
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: non_constant_identifier_names, non_constant_identifier_names, non_constant_identifier_names, non_constant_identifier_names
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    // ignore: deprecated_colon_for_default_value
//   // Remove the options parameter since it is not required
//   // options: DefaultFirebaseOptions.currentPlatform,
//  );
// /// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanBfFcPsrkrt7B3Edh7gMNo-b2BYKJF4',
    appId: '1:164148488292:web:09c9ff40cc39db7741d771',
    messagingSenderId: '164148488292',
    projectId: 'final-year-project-67cd1',
    authDomain: 'final-year-project-67cd1.firebaseapp.com',
    storageBucket: 'final-year-project-67cd1.appspot.com',
    measurementId: 'G-V2S4L3LEMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsr3EnzOPuuoluhXbA035VwzPeFRSJ4Ic',
    appId: '1:164148488292:android:80b22aa015e3c82941d771',
    messagingSenderId: '164148488292',
    projectId: 'final-year-project-67cd1',
    storageBucket: 'final-year-project-67cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaK6d5uDobAIUROG_twkzND0Me2ySRE4I',
    appId: '1:164148488292:ios:ffd2fe4757052f3841d771',
    messagingSenderId: '164148488292',
    projectId: 'final-year-project-67cd1',
    storageBucket: 'final-year-project-67cd1.appspot.com',
    iosBundleId: 'com.example.blackSigatoka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaK6d5uDobAIUROG_twkzND0Me2ySRE4I',
    appId: '1:164148488292:ios:ffd2fe4757052f3841d771',
    messagingSenderId: '164148488292',
    projectId: 'final-year-project-67cd1',
    storageBucket: 'final-year-project-67cd1.appspot.com',
    iosBundleId: 'com.example.blackSigatoka',
  );
}
